### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by MaxSecurity** [TideSec/FuzzScanner#6]
报错信息其中一部分:
", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files
Exception in thread Thread-27409:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "FuzzScanner.py", line 613, in connect_port
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files

Exception in thread Thread-27411:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "FuzzScanner.py", line 613, in connect_port
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files

Exception in thread Thread-27410:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "FuzzScanner.py", line 613, in connect_port
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files

Exception in thread Thread-27412:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner

**Comment by wu5jin7** [comment]
你联系方式呢？可以把你的QQ联系或者微信发给我邮箱吗？我的邮箱是wu5jin7@gmail.com

**Comment by TideSec** [comment]
这是linux系统的一种保护机制，可以执行一下ulimit -n 100000再试试，如果有效的话可以修改limits.conf 文件。
